# find wine
# vi -->  %s/.*/git diff -R & $WINEDIR\/&

WINEDIR=/Users/jmillard/Downloads/wine_with_compile

git diff -R wine/include/concurrencysal.h $WINEDIR/wine/include/concurrencysal.h
git diff -R wine/include/propidl.h $WINEDIR/wine/include/propidl.h
git diff -R wine/include/inaddr.h $WINEDIR/wine/include/inaddr.h
git diff -R wine/include/rpcdce.h $WINEDIR/wine/include/rpcdce.h
git diff -R wine/include/excpt.h $WINEDIR/wine/include/excpt.h
git diff -R wine/include/specstrings.h $WINEDIR/wine/include/specstrings.h
git diff -R wine/include/driverspecs.h $WINEDIR/wine/include/driverspecs.h
git diff -R wine/include/ole2.h $WINEDIR/wine/include/ole2.h
git diff -R wine/include/winsock.h $WINEDIR/wine/include/winsock.h
git diff -R wine/include/basetsd.h $WINEDIR/wine/include/basetsd.h
git diff -R wine/include/wincrypt.h $WINEDIR/wine/include/wincrypt.h
git diff -R wine/include/winternl.h $WINEDIR/wine/include/winternl.h
git diff -R wine/include/pshpack2.h $WINEDIR/wine/include/pshpack2.h
git diff -R wine/include/pshpack8.h $WINEDIR/wine/include/pshpack8.h
git diff -R wine/include/objidlbase.h $WINEDIR/wine/include/objidlbase.h
git diff -R wine/include/activscp.h $WINEDIR/wine/include/activscp.h
git diff -R wine/include/libloaderapi.h $WINEDIR/wine/include/libloaderapi.h
git diff -R wine/include/winnt.h $WINEDIR/wine/include/winnt.h
git diff -R wine/include/docobj.h $WINEDIR/wine/include/docobj.h
git diff -R wine/include/winnetwk.h $WINEDIR/wine/include/winnetwk.h
git diff -R wine/include/mmsystem.h $WINEDIR/wine/include/mmsystem.h
git diff -R wine/include/consoleapi.h $WINEDIR/wine/include/consoleapi.h
git diff -R wine/include/msxml.h $WINEDIR/wine/include/msxml.h
git diff -R wine/include/windef.h $WINEDIR/wine/include/windef.h
git diff -R wine/include/combaseapi.h $WINEDIR/wine/include/combaseapi.h
git diff -R wine/include/rpcdcep.h $WINEDIR/wine/include/rpcdcep.h
git diff -R wine/include/winnls.h $WINEDIR/wine/include/winnls.h
git diff -R wine/include/oleauto.h $WINEDIR/wine/include/oleauto.h
git diff -R wine/include/mshtmhst.h $WINEDIR/wine/include/mshtmhst.h
git diff -R wine/include/commdlg.h $WINEDIR/wine/include/commdlg.h
git diff -R wine/include/reason.h $WINEDIR/wine/include/reason.h
git diff -R wine/include/processthreadsapi.h $WINEDIR/wine/include/processthreadsapi.h
git diff -R wine/include/winapifamily.h $WINEDIR/wine/include/winapifamily.h
git diff -R wine/include/winnt.rh $WINEDIR/wine/include/winnt.rh
git diff -R wine/include/winsmcrd.h $WINEDIR/wine/include/winsmcrd.h
git diff -R wine/include/pshpack1.h $WINEDIR/wine/include/pshpack1.h
git diff -R wine/include/mcx.h $WINEDIR/wine/include/mcx.h
git diff -R wine/include/wine/debug.h $WINEDIR/wine/include/wine/debug.h
git diff -R wine/include/wine/test.h $WINEDIR/wine/include/wine/test.h
git diff -R wine/include/wine/list.h $WINEDIR/wine/include/wine/list.h
git diff -R wine/include/wine/heap.h $WINEDIR/wine/include/wine/heap.h
git diff -R wine/include/ocidl.h $WINEDIR/wine/include/ocidl.h
git diff -R wine/include/guiddef.h $WINEDIR/wine/include/guiddef.h
git diff -R wine/include/imm.h $WINEDIR/wine/include/imm.h
git diff -R wine/include/wincontypes.h $WINEDIR/wine/include/wincontypes.h
git diff -R wine/include/windows.h $WINEDIR/wine/include/windows.h
git diff -R wine/include/nb30.h $WINEDIR/wine/include/nb30.h
git diff -R wine/include/threadpoolapiset.h $WINEDIR/wine/include/threadpoolapiset.h
git diff -R wine/include/rpcproxy.h $WINEDIR/wine/include/rpcproxy.h
git diff -R wine/include/ntstatus.h $WINEDIR/wine/include/ntstatus.h
git diff -R wine/include/prsht.h $WINEDIR/wine/include/prsht.h
git diff -R wine/include/winreg.h $WINEDIR/wine/include/winreg.h
git diff -R wine/include/oleidl.h $WINEDIR/wine/include/oleidl.h
git diff -R wine/include/objidl.h $WINEDIR/wine/include/objidl.h
git diff -R wine/include/rpcsal.h $WINEDIR/wine/include/rpcsal.h
git diff -R wine/include/rpcasync.h $WINEDIR/wine/include/rpcasync.h
git diff -R wine/include/verrsrc.h $WINEDIR/wine/include/verrsrc.h
git diff -R wine/include/dispex.h $WINEDIR/wine/include/dispex.h
git diff -R wine/include/scarderr.h $WINEDIR/wine/include/scarderr.h
git diff -R wine/include/wincon.h $WINEDIR/wine/include/wincon.h
git diff -R wine/include/dde.h $WINEDIR/wine/include/dde.h
git diff -R wine/include/winscard.h $WINEDIR/wine/include/winscard.h
git diff -R wine/include/poppack.h $WINEDIR/wine/include/poppack.h
git diff -R wine/include/pshpack4.h $WINEDIR/wine/include/pshpack4.h
git diff -R wine/include/unknwn.h $WINEDIR/wine/include/unknwn.h
git diff -R wine/include/urlmon.h $WINEDIR/wine/include/urlmon.h
git diff -R wine/include/winerror.h $WINEDIR/wine/include/winerror.h
git diff -R wine/include/winioctl.h $WINEDIR/wine/include/winioctl.h
git diff -R wine/include/wingdi.h $WINEDIR/wine/include/wingdi.h
git diff -R wine/include/oaidl.h $WINEDIR/wine/include/oaidl.h
git diff -R wine/include/winuser.h $WINEDIR/wine/include/winuser.h
git diff -R wine/include/winspool.h $WINEDIR/wine/include/winspool.h
git diff -R wine/include/rpc.h $WINEDIR/wine/include/rpc.h
git diff -R wine/include/objbase.h $WINEDIR/wine/include/objbase.h
git diff -R wine/include/namespaceapi.h $WINEDIR/wine/include/namespaceapi.h
git diff -R wine/include/winperf.h $WINEDIR/wine/include/winperf.h
git diff -R wine/include/ddeml.h $WINEDIR/wine/include/ddeml.h
git diff -R wine/include/winuser.rh $WINEDIR/wine/include/winuser.rh
git diff -R wine/include/sal.h $WINEDIR/wine/include/sal.h
git diff -R wine/include/wtypes.h $WINEDIR/wine/include/wtypes.h
git diff -R wine/include/winver.h $WINEDIR/wine/include/winver.h
git diff -R wine/include/shellapi.h $WINEDIR/wine/include/shellapi.h
git diff -R wine/include/dde.rh $WINEDIR/wine/include/dde.rh
git diff -R wine/include/rpcndr.h $WINEDIR/wine/include/rpcndr.h
git diff -R wine/include/initguid.h $WINEDIR/wine/include/initguid.h
git diff -R wine/include/rpcnterr.h $WINEDIR/wine/include/rpcnterr.h
git diff -R wine/include/lzexpand.h $WINEDIR/wine/include/lzexpand.h
git diff -R wine/include/timezoneapi.h $WINEDIR/wine/include/timezoneapi.h
git diff -R wine/include/winsvc.h $WINEDIR/wine/include/winsvc.h
git diff -R wine/include/winbase.h $WINEDIR/wine/include/winbase.h
git diff -R wine/include/objsafe.h $WINEDIR/wine/include/objsafe.h
git diff -R wine/include/dlgs.h $WINEDIR/wine/include/dlgs.h
git diff -R wine/include/bcrypt.h $WINEDIR/wine/include/bcrypt.h
git diff -R wine/include/cderr.h $WINEDIR/wine/include/cderr.h
git diff -R wine/include/synchapi.h $WINEDIR/wine/include/synchapi.h
git diff -R wine/include/activdbg.h $WINEDIR/wine/include/activdbg.h
git diff -R wine/include/cguid.h $WINEDIR/wine/include/cguid.h
git diff -R wine/include/servprov.h $WINEDIR/wine/include/servprov.h
git diff -R wine/dlls/kernelbase/locale.c $WINEDIR/wine/dlls/kernelbase/locale.c
git diff -R wine/dlls/vbscript/parser.tab.c $WINEDIR/wine/dlls/vbscript/parser.tab.c
git diff -R wine/dlls/vbscript/compile.c $WINEDIR/wine/dlls/vbscript/compile.c
git diff -R wine/dlls/vbscript/vbdisp.c $WINEDIR/wine/dlls/vbscript/vbdisp.c
git diff -R wine/dlls/vbscript/vbscript.c $WINEDIR/wine/dlls/vbscript/vbscript.c
git diff -R wine/dlls/vbscript/vbscript_defs.h $WINEDIR/wine/dlls/vbscript/vbscript_defs.h
git diff -R wine/dlls/vbscript/lex.c $WINEDIR/wine/dlls/vbscript/lex.c
git diff -R wine/dlls/vbscript/interp.c $WINEDIR/wine/dlls/vbscript/interp.c
git diff -R wine/dlls/vbscript/parse.h $WINEDIR/wine/dlls/vbscript/parse.h
git diff -R wine/dlls/vbscript/regexp.c $WINEDIR/wine/dlls/vbscript/regexp.c
git diff -R wine/dlls/vbscript/vbsglobal.h $WINEDIR/wine/dlls/vbscript/vbsglobal.h
git diff -R wine/dlls/vbscript/vbscript.h $WINEDIR/wine/dlls/vbscript/vbscript.h
git diff -R wine/dlls/vbscript/utils.c $WINEDIR/wine/dlls/vbscript/utils.c
git diff -R wine/dlls/vbscript/parser.tab.h $WINEDIR/wine/dlls/vbscript/parser.tab.h
git diff -R wine/dlls/vbscript/vbsregexp55.h $WINEDIR/wine/dlls/vbscript/vbsregexp55.h
git diff -R wine/dlls/vbscript/vbscript_main.c $WINEDIR/wine/dlls/vbscript/vbscript_main.c
git diff -R wine/dlls/vbscript/vbregexp.c $WINEDIR/wine/dlls/vbscript/vbregexp.c
git diff -R wine/dlls/vbscript/global.c $WINEDIR/wine/dlls/vbscript/global.c
git diff -R wine/dlls/vbscript/vbscript_classes.h $WINEDIR/wine/dlls/vbscript/vbscript_classes.h
git diff -R wine/dlls/vbscript/regexp.h $WINEDIR/wine/dlls/vbscript/regexp.h
git diff -R wine/dlls/oleaut32/oleaut.c $WINEDIR/wine/dlls/oleaut32/oleaut.c
git diff -R wine/dlls/oleaut32/variant.c $WINEDIR/wine/dlls/oleaut32/variant.c
git diff -R wine/dlls/oleaut32/vartype.c $WINEDIR/wine/dlls/oleaut32/vartype.c
git diff -R wine/dlls/oleaut32/resource.h $WINEDIR/wine/dlls/oleaut32/resource.h
git diff -R wine/dlls/oleaut32/variant.h $WINEDIR/wine/dlls/oleaut32/variant.h
git diff -R wine/dlls/oleaut32/safearray.c $WINEDIR/wine/dlls/oleaut32/safearray.c
git diff -R wine/dlls/oleaut32/varformat.c $WINEDIR/wine/dlls/oleaut32/varformat.c
git diff -R wine/dlls/oleaut32/typelib.h $WINEDIR/wine/dlls/oleaut32/typelib.h
git diff -R wine/dlls/oleaut32/oleaut32_oaidl.h $WINEDIR/wine/dlls/oleaut32/oleaut32_oaidl.h